#!/bin/zsh

: ${ITERATIONS:=100000}
: ${CORPUS:=tvscripts}

. ~/.rvm/scripts/rvm

FORMAT=$1
if [ -z "$FORMAT" ]; then
   echo "You must specify a format as first param" >&2
   exit 1
fi
PROF=`which ruby-prof`

bundle exec /usr/bin/time -l ruby -Ilib $PROF -f prof-$FORMAT-$CORPUS.html \
    -p graph_html -- ./bin/chbs --trace generate -c corpus/$CORPUS.$FORMAT \
    -n $ITERATIONS > /dev/null
